import type { Ranking } from "../types";

/**
 * Top 10 Biggest Tech Acquisitions Ever — through 2024.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   Company filings
 *   https://en.wikipedia.org/wiki/List_of_largest_mergers_and_acquisitions
 */

const ranking: Ranking = {
  slug: "biggest-tech-acquisitions",
  title: "Top 10 Biggest Tech Acquisitions Ever",
  metricLabel: "deal size",
  format: "usd-b",
  asOfDate: "through 2024",
  verifiedOnISO: "2026-08-14",
  sources: [
    "Company filings",
    "https://en.wikipedia.org/wiki/List_of_largest_mergers_and_acquisitions",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"Activision Blizzard","value":75.4,"image":"/ranking/assets/biggest-tech-acquisitions/01-activision-blizzard.jpg","note":"Microsoft, 2023"},
    {"rank":2,"name":"VMware","value":69,"image":"/ranking/assets/biggest-tech-acquisitions/02-vmware.jpg","note":"Broadcom, 2023"},
    {"rank":3,"name":"EMC","value":67,"image":"/ranking/assets/biggest-tech-acquisitions/03-emc.png","note":"Dell, 2016"},
    {"rank":4,"name":"Twitter","value":44,"image":"/ranking/assets/biggest-tech-acquisitions/04-twitter.png","note":"Elon Musk, 2022"},
    {"rank":5,"name":"Red Hat","value":34,"image":"/ranking/assets/biggest-tech-acquisitions/05-red-hat.jpeg","note":"IBM, 2019"},
    {"rank":6,"name":"Splunk","value":28,"image":"/ranking/assets/biggest-tech-acquisitions/06-splunk.jpg","note":"Cisco, 2024"},
    {"rank":7,"name":"Slack","value":27.7,"image":"/ranking/assets/biggest-tech-acquisitions/07-slack.png","note":"Salesforce, 2021"},
    {"rank":8,"name":"LinkedIn","value":26.2,"image":"/ranking/assets/biggest-tech-acquisitions/08-linkedin.png","note":"Microsoft, 2016"},
    {"rank":9,"name":"Compaq","value":25,"image":"/ranking/assets/biggest-tech-acquisitions/09-compaq.png","note":"HP, 2002"},
    {"rank":10,"name":"Nuance","value":19.7,"image":"/ranking/assets/biggest-tech-acquisitions/10-nuance.png","note":"Microsoft, 2022"},
  ],
};

export default ranking;
