import type { Ranking } from "../types";

/**
 * Top 10 Biggest Company Bankruptcies Ever — historical.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   https://www.bankruptcydata.com/
 *   https://en.wikipedia.org/wiki/List_of_largest_bankruptcies_in_US_history
 */

const ranking: Ranking = {
  slug: "biggest-bankruptcies-ever",
  title: "Top 10 Biggest Company Bankruptcies Ever",
  metricLabel: "assets at filing",
  format: "usd-b",
  asOfDate: "historical",
  verifiedOnISO: "2026-08-14",
  sources: [
    "https://www.bankruptcydata.com/",
    "https://en.wikipedia.org/wiki/List_of_largest_bankruptcies_in_US_history",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"Lehman Brothers","value":691,"image":null,"note":"2008 — trigger of the GFC"},
    {"rank":2,"name":"Washington Mutual","value":328,"image":null,"note":"2008"},
    {"rank":3,"name":"First Republic Bank","value":229,"image":null,"note":"2023"},
    {"rank":4,"name":"Silicon Valley Bank","value":209,"image":null,"note":"2023"},
    {"rank":5,"name":"Signature Bank","value":110,"image":null,"note":"2023"},
    {"rank":6,"name":"WorldCom","value":104,"image":null,"note":"2002 — accounting fraud"},
    {"rank":7,"name":"General Motors","value":91,"image":null,"note":"2009"},
    {"rank":8,"name":"CIT Group","value":71,"image":null,"note":"2009"},
    {"rank":9,"name":"Enron","value":66,"image":null,"note":"2001 — accounting fraud"},
    {"rank":10,"name":"Conseco","value":61,"image":null,"note":"2002"},
  ],
};

export default ranking;
