import type { Ranking } from "../types";

/**
 * Top 10 Fastest Companies to $1B — historical.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   CB Insights unicorn timelines
 *   Company news archives
 */

const ranking: Ranking = {
  slug: "fastest-to-1b-valuation",
  title: "Top 10 Fastest Companies to $1B",
  metricLabel: "months to unicorn",
  format: "int",
  asOfDate: "historical",
  verifiedOnISO: "2026-08-15",
  sources: [
    "CB Insights unicorn timelines",
    "Company news archives",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"Jio Platforms","value":5,"image":"/ranking/assets/fastest-to-1b-valuation/01-jio-platforms.png","note":"reached $1B in months via strategic invests"},
    {"rank":2,"name":"Jet.com","value":6,"image":"/ranking/assets/fastest-to-1b-valuation/02-jet-com.jpg","note":"6 months to unicorn"},
    {"rank":3,"name":"Bird","value":12,"image":"/ranking/assets/fastest-to-1b-valuation/03-bird.png","note":"scooter startup"},
    {"rank":4,"name":"Ola Cabs","value":18,"image":"/ranking/assets/fastest-to-1b-valuation/04-ola-cabs.png"},
    {"rank":5,"name":"Deel","value":20,"image":"/ranking/assets/fastest-to-1b-valuation/05-deel.png"},
    {"rank":6,"name":"Roblox","value":24,"image":"/ranking/assets/fastest-to-1b-valuation/06-roblox.jpg"},
    {"rank":7,"name":"Snap","value":24,"image":"/ranking/assets/fastest-to-1b-valuation/07-snap.png","note":"Snapchat parent"},
    {"rank":8,"name":"Slack","value":24,"image":"/ranking/assets/fastest-to-1b-valuation/08-slack.jpg"},
    {"rank":9,"name":"Instacart","value":30,"image":"/ranking/assets/fastest-to-1b-valuation/09-instacart.png"},
    {"rank":10,"name":"Brex","value":36,"image":"/ranking/assets/fastest-to-1b-valuation/10-brex.png"},
  ],
};

export default ranking;
