import type { Ranking } from "../types";

/**
 * Top 10 Highest-Grossing Movies — through 2024.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   https://www.boxofficemojo.com/chart/ww_top_lifetime_gross/
 */

const ranking: Ranking = {
  slug: "highest-grossing-movies",
  title: "Top 10 Highest-Grossing Movies",
  metricLabel: "worldwide box office",
  format: "usd-b1",
  asOfDate: "through 2024",
  verifiedOnISO: "2026-08-15",
  sources: [
    "https://www.boxofficemojo.com/chart/ww_top_lifetime_gross/",
  ],
  portraitBg: "dark",
  entries: [
    {"rank":1,"name":"Avatar","value":2.92,"image":"/ranking/assets/highest-grossing-movies/01-avatar.jpg","note":"2009"},
    {"rank":2,"name":"Avengers: Endgame","value":2.8,"image":"/ranking/assets/highest-grossing-movies/02-avengers-endgame.jpg","note":"2019"},
    {"rank":3,"name":"Avatar: The Way of Water","value":2.32,"image":"/ranking/assets/highest-grossing-movies/03-avatar-the-way-of-water.jpg","note":"2022"},
    {"rank":4,"name":"Titanic","value":2.26,"image":"/ranking/assets/highest-grossing-movies/04-titanic.png","note":"1997"},
    {"rank":5,"name":"Star Wars: The Force Awakens","value":2.07,"image":"/ranking/assets/highest-grossing-movies/05-star-wars-the-force-awak.jpg","note":"2015"},
    {"rank":6,"name":"Avengers: Infinity War","value":2.05,"image":"/ranking/assets/highest-grossing-movies/06-avengers-infinity-war.jpg","note":"2018"},
    {"rank":7,"name":"Spider-Man: No Way Home","value":1.92,"image":"/ranking/assets/highest-grossing-movies/07-spider-man-no-way-home.jpg","note":"2021"},
    {"rank":8,"name":"Inside Out 2","value":1.7,"image":"/ranking/assets/highest-grossing-movies/08-inside-out-2.jpg","note":"2024"},
    {"rank":9,"name":"Jurassic World","value":1.67,"image":"/ranking/assets/highest-grossing-movies/09-jurassic-world.jpg","note":"2015"},
    {"rank":10,"name":"The Lion King","value":1.66,"image":"/ranking/assets/highest-grossing-movies/10-the-lion-king.jpg","note":"2019 remake"},
  ],
};

export default ranking;
