import type { Ranking } from "../types";

/**
 * Top 10 Highest-Paid CEOs — 2024 reporting.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   https://aflcio.org/paywatch
 *   https://www.equilar.com/reports/100-highest-paid-ceos.html
 */

const ranking: Ranking = {
  slug: "highest-paid-ceos-2026",
  title: "Top 10 Highest-Paid CEOs",
  metricLabel: "annual pay",
  format: "usd-m",
  asOfDate: "2024 reporting",
  verifiedOnISO: "2026-08-14",
  sources: [
    "https://aflcio.org/paywatch",
    "https://www.equilar.com/reports/100-highest-paid-ceos.html",
  ],
  portraitBg: "dark",
  entries: [
    {"rank":1,"name":"Alex Karp","value":1098,"image":"/ranking/assets/highest-paid-ceos-2026/01-alex-karp.jpg","note":"Palantir — mega equity grant"},
    {"rank":2,"name":"Sundar Pichai","value":226,"image":"/ranking/assets/highest-paid-ceos-2026/02-sundar-pichai.jpg","note":"Alphabet"},
    {"rank":3,"name":"Hock Tan","value":162,"image":"/ranking/assets/highest-paid-ceos-2026/03-hock-tan.png","note":"Broadcom"},
    {"rank":4,"name":"Nikesh Arora","value":151,"image":"/ranking/assets/highest-paid-ceos-2026/04-nikesh-arora.jpg","note":"Palo Alto Networks"},
    {"rank":5,"name":"Satya Nadella","value":79,"image":"/ranking/assets/highest-paid-ceos-2026/05-satya-nadella.jpg","note":"Microsoft"},
    {"rank":6,"name":"Tim Cook","value":63,"image":"/ranking/assets/highest-paid-ceos-2026/06-tim-cook.jpg","note":"Apple"},
    {"rank":7,"name":"Ted Sarandos","value":50,"image":"/ranking/assets/highest-paid-ceos-2026/07-ted-sarandos.jpg","note":"Netflix"},
    {"rank":8,"name":"Jamie Dimon","value":36,"image":"/ranking/assets/highest-paid-ceos-2026/08-jamie-dimon.jpg","note":"JPMorgan Chase"},
    {"rank":9,"name":"Andy Jassy","value":29,"image":"/ranking/assets/highest-paid-ceos-2026/09-andy-jassy.jpg","note":"Amazon"},
    {"rank":10,"name":"Mark Zuckerberg","value":27,"image":"/ranking/assets/highest-paid-ceos-2026/10-mark-zuckerberg.jpg","note":"Meta — largely security"},
  ],
};

export default ranking;
