import type { Ranking } from "../types";

/**
 * Top 10 Largest IPOs in History — through 2024.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   Exchange data
 *   https://en.wikipedia.org/wiki/List_of_largest_initial_public_offerings
 */

const ranking: Ranking = {
  slug: "largest-ipos-history",
  title: "Top 10 Largest IPOs in History",
  metricLabel: "capital raised",
  format: "usd-b1",
  asOfDate: "through 2024",
  verifiedOnISO: "2026-08-15",
  sources: [
    "Exchange data",
    "https://en.wikipedia.org/wiki/List_of_largest_initial_public_offerings",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"Saudi Aramco","value":29.4,"image":"/ranking/assets/largest-ipos-history/01-saudi-aramco.png","note":"2019"},
    {"rank":2,"name":"Alibaba","value":25,"image":"/ranking/assets/largest-ipos-history/02-alibaba.jpg","note":"2014"},
    {"rank":3,"name":"SoftBank Corp","value":23.5,"image":"/ranking/assets/largest-ipos-history/03-softbank-corp.jpg","note":"2018"},
    {"rank":4,"name":"Agricultural Bank of China","value":22.1,"image":"/ranking/assets/largest-ipos-history/04-agricultural-bank-of-chi.jpg","note":"2010"},
    {"rank":5,"name":"NTT DoCoMo","value":18.4,"image":"/ranking/assets/largest-ipos-history/05-ntt-docomo.jpg","note":"1998"},
    {"rank":6,"name":"Visa","value":17.9,"image":"/ranking/assets/largest-ipos-history/06-visa.jpg","note":"2008"},
    {"rank":7,"name":"AIA Group","value":17.8,"image":"/ranking/assets/largest-ipos-history/07-aia-group.png","note":"2010"},
    {"rank":8,"name":"Enel","value":17.4,"image":"/ranking/assets/largest-ipos-history/08-enel.jpg","note":"1999"},
    {"rank":9,"name":"Facebook","value":16,"image":"/ranking/assets/largest-ipos-history/09-facebook.png","note":"2012"},
    {"rank":10,"name":"General Motors","value":15.8,"image":"/ranking/assets/largest-ipos-history/10-general-motors.jpg","note":"2010 re-IPO"},
  ],
};

export default ranking;
