import type { Ranking } from "../types";

/**
 * Top 10 Most Valuable Car Companies — August 2026.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   https://companiesmarketcap.com/automakers/largest-automakers-by-market-cap/
 */

const ranking: Ranking = {
  slug: "most-valuable-car-companies",
  title: "Top 10 Most Valuable Car Companies",
  metricLabel: "market cap",
  format: "usd-b",
  asOfDate: "August 2026",
  verifiedOnISO: "2026-08-15",
  sources: [
    "https://companiesmarketcap.com/automakers/largest-automakers-by-market-cap/",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"Tesla","value":1100,"image":"/ranking/assets/most-valuable-car-companies/01-tesla.webp"},
    {"rank":2,"name":"Toyota","value":290,"image":"/ranking/assets/most-valuable-car-companies/02-toyota.webp"},
    {"rank":3,"name":"BYD","value":100,"image":"/ranking/assets/most-valuable-car-companies/03-byd.png"},
    {"rank":4,"name":"Ferrari","value":85,"image":"/ranking/assets/most-valuable-car-companies/04-ferrari.webp"},
    {"rank":5,"name":"BMW","value":60,"image":"/ranking/assets/most-valuable-car-companies/05-bmw.webp"},
    {"rank":6,"name":"General Motors","value":60,"image":"/ranking/assets/most-valuable-car-companies/06-general-motors.webp"},
    {"rank":7,"name":"Mercedes-Benz","value":55,"image":"/ranking/assets/most-valuable-car-companies/07-mercedes-benz.webp"},
    {"rank":8,"name":"Porsche","value":55,"image":"/ranking/assets/most-valuable-car-companies/08-porsche.webp"},
    {"rank":9,"name":"Volkswagen","value":50,"image":"/ranking/assets/most-valuable-car-companies/09-volkswagen.png"},
    {"rank":10,"name":"Stellantis","value":50,"image":"/ranking/assets/most-valuable-car-companies/10-stellantis.webp"},
  ],
};

export default ranking;
