import type { Ranking } from "../types";

/**
 * Top 10 Most Valuable Startups — 2024.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   https://www.cbinsights.com/research-unicorn-companies
 */

const ranking: Ranking = {
  slug: "most-valuable-startups",
  title: "Top 10 Most Valuable Startups",
  metricLabel: "valuation",
  format: "usd-b",
  asOfDate: "2024",
  verifiedOnISO: "2026-08-15",
  sources: [
    "https://www.cbinsights.com/research-unicorn-companies",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"SpaceX","value":350,"image":"/ranking/assets/most-valuable-startups/01-spacex.jpg","note":"Elon Musk"},
    {"rank":2,"name":"ByteDance","value":220,"image":"/ranking/assets/most-valuable-startups/02-bytedance.jpg","note":"TikTok parent"},
    {"rank":3,"name":"OpenAI","value":157,"image":"/ranking/assets/most-valuable-startups/03-openai.png"},
    {"rank":4,"name":"Stripe","value":91,"image":"/ranking/assets/most-valuable-startups/04-stripe.jpg"},
    {"rank":5,"name":"SHEIN","value":66,"image":"/ranking/assets/most-valuable-startups/05-shein.png"},
    {"rank":6,"name":"Databricks","value":62,"image":"/ranking/assets/most-valuable-startups/06-databricks.jpg"},
    {"rank":7,"name":"xAI","value":50,"image":"/ranking/assets/most-valuable-startups/07-xai.png","note":"Elon Musk"},
    {"rank":8,"name":"Revolut","value":45,"image":"/ranking/assets/most-valuable-startups/08-revolut.jpg"},
    {"rank":9,"name":"Canva","value":32,"image":"/ranking/assets/most-valuable-startups/09-canva.png"},
    {"rank":10,"name":"Fanatics","value":31,"image":"/ranking/assets/most-valuable-startups/10-fanatics.jpg"},
  ],
};

export default ranking;
