import type { Ranking } from "../types";

/**
 * Top 10 Most Valuable Brands — 2025 rankings.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   https://interbrand.com/best-global-brands/
 */

const ranking: Ranking = {
  slug: "most-valuable-brands-2026",
  title: "Top 10 Most Valuable Brands",
  metricLabel: "brand value",
  format: "usd-b",
  asOfDate: "2025 rankings",
  verifiedOnISO: "2026-08-13",
  sources: [
    "https://interbrand.com/best-global-brands/",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"Apple","value":488,"image":"/ranking/assets/most-valuable-brands-2026/01-apple.webp"},
    {"rank":2,"name":"Microsoft","value":353,"image":"/ranking/assets/most-valuable-brands-2026/02-microsoft.webp"},
    {"rank":3,"name":"Amazon","value":298,"image":"/ranking/assets/most-valuable-brands-2026/03-amazon.webp"},
    {"rank":4,"name":"Google","value":292,"image":"/ranking/assets/most-valuable-brands-2026/04-google.webp"},
    {"rank":5,"name":"Samsung","value":100,"image":"/ranking/assets/most-valuable-brands-2026/05-samsung.webp"},
    {"rank":6,"name":"Toyota","value":68,"image":"/ranking/assets/most-valuable-brands-2026/06-toyota.webp"},
    {"rank":7,"name":"Coca-Cola","value":61,"image":"/ranking/assets/most-valuable-brands-2026/07-coca-cola.webp"},
    {"rank":8,"name":"Mercedes-Benz","value":60,"image":"/ranking/assets/most-valuable-brands-2026/08-mercedes-benz.webp"},
    {"rank":9,"name":"McDonald's","value":53,"image":"/ranking/assets/most-valuable-brands-2026/09-mcdonald-s.webp"},
    {"rank":10,"name":"BMW","value":51,"image":"/ranking/assets/most-valuable-brands-2026/10-bmw.webp"},
  ],
};

export default ranking;
