import type { Ranking } from "../types";

/**
 * Top 10 Most Profitable Companies — latest fiscal year.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   https://fortune.com/global500/
 *   Company 10-K filings
 */

const ranking: Ranking = {
  slug: "most-profitable-companies-2026",
  title: "Top 10 Most Profitable Companies",
  metricLabel: "annual profit",
  format: "usd-b",
  asOfDate: "latest fiscal year",
  verifiedOnISO: "2026-08-14",
  sources: [
    "https://fortune.com/global500/",
    "Company 10-K filings",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"Saudi Aramco","value":106,"image":"/ranking/assets/most-profitable-companies-2026/01-saudi-aramco.webp"},
    {"rank":2,"name":"Apple","value":97,"image":"/ranking/assets/most-profitable-companies-2026/02-apple.webp"},
    {"rank":3,"name":"Berkshire Hathaway","value":96,"image":"/ranking/assets/most-profitable-companies-2026/03-berkshire-hathaway.jpg"},
    {"rank":4,"name":"Microsoft","value":88,"image":"/ranking/assets/most-profitable-companies-2026/04-microsoft.webp"},
    {"rank":5,"name":"Alphabet","value":74,"image":"/ranking/assets/most-profitable-companies-2026/05-alphabet.webp"},
    {"rank":6,"name":"Meta","value":62,"image":"/ranking/assets/most-profitable-companies-2026/06-meta.webp"},
    {"rank":7,"name":"ICBC","value":51,"image":"/ranking/assets/most-profitable-companies-2026/07-icbc.webp"},
    {"rank":8,"name":"JPMorgan Chase","value":50,"image":"/ranking/assets/most-profitable-companies-2026/08-jpmorgan-chase.webp"},
    {"rank":9,"name":"ExxonMobil","value":36,"image":"/ranking/assets/most-profitable-companies-2026/09-exxonmobil.webp"},
    {"rank":10,"name":"Amazon","value":30,"image":"/ranking/assets/most-profitable-companies-2026/10-amazon.webp"},
  ],
};

export default ranking;
