import type { Ranking } from "../types";

/**
 * Top 10 Most Downloaded Apps of All Time — cumulative through 2024.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   https://www.data.ai/
 *   https://sensortower.com/
 */

const ranking: Ranking = {
  slug: "most-downloaded-apps-alltime",
  title: "Top 10 Most Downloaded Apps of All Time",
  metricLabel: "downloads",
  format: "num-b",
  asOfDate: "cumulative through 2024",
  verifiedOnISO: "2026-08-14",
  sources: [
    "https://www.data.ai/",
    "https://sensortower.com/",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"Facebook","value":6,"image":"/ranking/assets/most-downloaded-apps-alltime/01-facebook.png","note":"Meta"},
    {"rank":2,"name":"WhatsApp","value":5.8,"image":"/ranking/assets/most-downloaded-apps-alltime/02-whatsapp.png","note":"Meta"},
    {"rank":3,"name":"Instagram","value":5.3,"image":"/ranking/assets/most-downloaded-apps-alltime/03-instagram.png","note":"Meta"},
    {"rank":4,"name":"Messenger","value":5.2,"image":"/ranking/assets/most-downloaded-apps-alltime/04-messenger.png","note":"Meta"},
    {"rank":5,"name":"TikTok","value":4.7,"image":"/ranking/assets/most-downloaded-apps-alltime/05-tiktok.png","note":"ByteDance — excl. Douyin"},
    {"rank":6,"name":"YouTube","value":3,"image":"/ranking/assets/most-downloaded-apps-alltime/06-youtube.png","note":"Alphabet"},
    {"rank":7,"name":"Snapchat","value":2.5,"image":"/ranking/assets/most-downloaded-apps-alltime/07-snapchat.png","note":"Snap Inc"},
    {"rank":8,"name":"Twitter","value":2.3,"image":"/ranking/assets/most-downloaded-apps-alltime/08-twitter.png","note":"now X"},
    {"rank":9,"name":"Zoom","value":1.5,"image":"/ranking/assets/most-downloaded-apps-alltime/09-zoom.png","note":"pandemic surge"},
    {"rank":10,"name":"Telegram","value":1.5,"image":"/ranking/assets/most-downloaded-apps-alltime/10-telegram.png"},
  ],
};

export default ranking;
