import type { Ranking } from "../types";

/**
 * Top 10 Most Valuable Sports Teams — 2024.
 *
 * AUTO-GENERATED by scripts/build-ranking.ts. Re-run the builder rather
 * than hand-editing — hand edits will be wiped on the next build.
 *
 * Sources:
 *   https://www.forbes.com/sports-money/
 *   https://www.sportico.com/valuations/
 */

const ranking: Ranking = {
  slug: "most-valuable-sports-teams",
  title: "Top 10 Most Valuable Sports Teams",
  metricLabel: "franchise value",
  format: "usd-b",
  asOfDate: "2024",
  verifiedOnISO: "2026-08-15",
  sources: [
    "https://www.forbes.com/sports-money/",
    "https://www.sportico.com/valuations/",
  ],
  portraitBg: "light",
  entries: [
    {"rank":1,"name":"Dallas Cowboys","value":10.1,"image":"/ranking/assets/most-valuable-sports-teams/01-dallas-cowboys.png","note":"NFL"},
    {"rank":2,"name":"Golden State Warriors","value":8.8,"image":"/ranking/assets/most-valuable-sports-teams/02-golden-state-warriors.png","note":"NBA"},
    {"rank":3,"name":"Los Angeles Rams","value":7.6,"image":"/ranking/assets/most-valuable-sports-teams/03-los-angeles-rams.png","note":"NFL"},
    {"rank":4,"name":"New York Yankees","value":7.5,"image":"/ranking/assets/most-valuable-sports-teams/04-new-york-yankees.png","note":"MLB"},
    {"rank":5,"name":"New York Knicks","value":7.5,"image":"/ranking/assets/most-valuable-sports-teams/05-new-york-knicks.png","note":"NBA"},
    {"rank":6,"name":"New England Patriots","value":7.4,"image":"/ranking/assets/most-valuable-sports-teams/06-new-england-patriots.png","note":"NFL"},
    {"rank":7,"name":"Los Angeles Lakers","value":7.1,"image":"/ranking/assets/most-valuable-sports-teams/07-los-angeles-lakers.png","note":"NBA"},
    {"rank":8,"name":"Real Madrid","value":6.7,"image":"/ranking/assets/most-valuable-sports-teams/08-real-madrid.png","note":"soccer"},
    {"rank":9,"name":"Manchester United","value":6.2,"image":"/ranking/assets/most-valuable-sports-teams/09-manchester-united.png","note":"soccer"},
    {"rank":10,"name":"FC Barcelona","value":5.6,"image":"/ranking/assets/most-valuable-sports-teams/10-fc-barcelona.png","note":"soccer"},
  ],
};

export default ranking;
